/**
 * SOAP note export utilities.
 * Formats a signed note as plain text and provides three export methods:
 *   1. Copy to clipboard — paste into any EMR text field
 *   2. Share via Web Share API — opens native share sheet (WhatsApp, email, etc.)
 *   3. Download as .txt — saves the note as a file
 *
 * These are the three practical ways to get a KliniK note into a hospital
 * EMR that has no API integration. All three require zero IT involvement.
 */

import { getDoctorProfile } from '../services/doctorProfile';

export interface NoteExportData {
    patientName: string;
    hospitalNumber: string;
    diagnosis: string;
    /** ISO timestamp when the note was signed */
    signedAt: string;
    /** Formatted SOAP sections */
    subjective: string;
    objective: string;
    assessment: string;
    plan: string;
}

/**
 * Formats a SOAP note as clean plain text suitable for pasting into any EMR.
 * The format is intentionally simple — no markdown, no special characters —
 * so it pastes cleanly into every EMR system without formatting noise.
 *
 * @param data - The note data to format
 * @returns Plain text note ready to paste or share
 */
export function formatNoteAsText(data: NoteExportData): string {
    const dateStr = new Date(data.signedAt).toLocaleString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: true,
    });

    return [
        '===== WARD ROUND NOTE =====',
        `Patient  : ${data.patientName}`,
        `Hosp No  : ${data.hospitalNumber}`,
        `Diagnosis: ${data.diagnosis}`,
        `Date/Time: ${dateStr}`,
        '',
        'SUBJECTIVE',
        '-----------',
        data.subjective,
        '',
        'OBJECTIVE',
        '----------',
        data.objective,
        '',
        'ASSESSMENT',
        '-----------',
        data.assessment,
        '',
        'PLAN',
        '-----',
        data.plan,
        '',
        '---',
        `Generated by KliniK AI Scribe — ${getDoctorProfile()?.hospitalName ?? 'KliniK'}.`,
        'All AI-generated content reviewed and confirmed by the treating doctor.',
        '===========================',
    ].join('\n');
}

/**
 * Copies formatted note text to the device clipboard.
 * Doctor can then paste directly into any EMR text field.
 *
 * @param text - Pre-formatted note text
 * @returns true if copy succeeded, false if clipboard access was denied
 */
export async function copyToClipboard(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        // Clipboard API blocked (older Android WebViews, some hospital kiosk browsers)
        // Fall back to the legacy execCommand method
        try {
            const el = document.createElement('textarea');
            el.value = text;
            el.style.position = 'fixed';
            el.style.opacity = '0';
            document.body.appendChild(el);
            el.select();
            const ok = document.execCommand('copy');
            document.body.removeChild(el);
            return ok;
        } catch {
            return false;
        }
    }
}

/**
 * Opens the device's native share sheet with the note text.
 * On Android/iOS this gives the doctor WhatsApp, email, messages,
 * and any other installed app as a share target — practical for Indian
 * hospitals where WhatsApp is commonly used for clinical communication.
 *
 * Falls back to clipboard copy if Web Share API is not available
 * (desktop browsers, older Android).
 *
 * @param text - Pre-formatted note text
 * @param patientName - Used as the share title
 * @returns true if share or clipboard copy succeeded
 */
export async function shareNote(text: string, patientName: string): Promise<boolean> {
    if (navigator.share) {
        try {
            await navigator.share({
                title: `Ward Round Note — ${patientName}`,
                text,
            });
            return true;
        } catch (err) {
            // User cancelled the share sheet — not an error
            if (err instanceof Error && err.name === 'AbortError') return false;
            // API exists but failed — fall through to clipboard
        }
    }
    // Web Share not available — copy to clipboard as fallback
    return copyToClipboard(text);
}

/**
 * Triggers a .txt file download of the note to the device.
 * On Android tablets this saves to Downloads. On desktop to the downloads folder.
 * The file can be emailed, uploaded to the hospital system, or attached to a record.
 *
 * @param text - Pre-formatted note text
 * @param patientName - Used to build the filename
 * @param signedAt - ISO timestamp for the filename
 */
export function downloadNoteAsText(
    text: string,
    patientName: string,
    signedAt: string,
): void {
    const date = new Date(signedAt)
        .toISOString()
        .slice(0, 10); // YYYY-MM-DD
    const safeName = patientName.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_');
    const rawPrefix = getDoctorProfile()?.hospitalName ?? 'KliniK';
    const safePrefix = rawPrefix.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_');
    const filename = `${safePrefix}_Note_${safeName}_${date}.txt`;

    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
